#!/usr/bin/env python3
"""Build the wiki skeleton from seed lists.

Responsibilities (in order):
  1. Create missing topic pages from `data/topic_seed_list.yaml`.
  2. Create missing concept pages from `data/concept_seed_list.yaml`.
  3. Never overwrite existing page bodies.
  4. Regenerate `wiki/index.md`.
  5. Append a dated line to `wiki/log.md`.
  6. Validate frontmatter on every wiki page (warnings only).

This tool is the only one allowed to write into `wiki/` during normal
operation. It refuses to touch anything under `raw/` or `staging/`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

import frontmatter

from utils import (
    CONCEPTS_DIR,
    CONCEPT_SEEDS,
    INDEX_PATH,
    LOG_PATH,
    QA_DIR,
    TEMPLATES_DIR,
    TOPICS_DIR,
    TOPIC_SEEDS,
    WIKI_DIR,
    humanize,
    load_yaml,
    now_iso,
    read_markdown,
    render_template,
    today_iso,
)

ALLOWED_TYPES = {"topic", "concept", "qa", "meta"}
ALLOWED_STATUS = {"draft", "reviewed", "locked"}
REQUIRED_FIELDS = ("id", "type", "cfa_topic", "status")
TYPE_PREFIXES = ("topic_", "concept_", "qa_")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--mode",
        choices=("init",),
        default="init",
        help="Build mode. Only 'init' is implemented.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Page creation from seeds
# ---------------------------------------------------------------------------

def _seed_list(yaml_path: Path, key: str) -> list[str]:
    data = load_yaml(yaml_path)
    values = data.get(key, []) or []
    if not isinstance(values, list):
        raise ValueError(f"{yaml_path}: expected a list under '{key}'")
    return [str(v).strip() for v in values if str(v).strip()]


def _create_from_template(
    *,
    slug: str,
    template_name: str,
    target_dir: Path,
) -> bool:
    """Create `<target_dir>/<slug>.md` from a template if it does not exist."""
    target = target_dir / f"{slug}.md"
    if target.exists():
        return False

    template_path = TEMPLATES_DIR / template_name
    rendered = render_template(
        template_path,
        slug=slug,
        title=humanize(slug),
        date=today_iso(),
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    return True


def create_topics() -> int:
    created = 0
    for slug in _seed_list(TOPIC_SEEDS, "topics"):
        if _create_from_template(
            slug=slug,
            template_name="topic.md",
            target_dir=TOPICS_DIR,
        ):
            created += 1
    return created


def create_concepts() -> int:
    created = 0
    for slug in _seed_list(CONCEPT_SEEDS, "concepts"):
        if _create_from_template(
            slug=slug,
            template_name="concept.md",
            target_dir=CONCEPTS_DIR,
        ):
            created += 1
    return created


# ---------------------------------------------------------------------------
# Index regeneration
# ---------------------------------------------------------------------------

def _list_pages(directory: Path) -> list[Path]:
    if not directory.exists():
        return []
    return sorted(
        p for p in directory.glob("*.md")
        if p.name not in {"index.md", "log.md"} and p.is_file()
    )


def _link_for(page: Path, folder_name: str) -> str:
    try:
        post = read_markdown(page)
    except Exception:  # noqa: BLE001
        post = None
    title = None
    if post is not None:
        raw_title = post.metadata.get("title")
        if isinstance(raw_title, str) and raw_title.strip():
            title = raw_title.strip()
    if not title:
        title = humanize(page.stem)
    return f"- [{title}]({folder_name}/{page.name})"


def _section(heading: str, folder_name: str, directory: Path) -> list[str]:
    lines = [f"## {heading}", ""]
    pages = _list_pages(directory)
    if not pages:
        lines.append("_(none yet)_")
    else:
        lines.extend(_link_for(p, folder_name) for p in pages)
    lines.append("")
    return lines


def regenerate_index() -> None:
    body_lines: list[str] = [
        "---",
        "id: index",
        "type: meta",
        'cfa_topic: ""',
        "status: draft",
        "title: Index",
        "---",
        "",
        "# Index",
        "",
        "_Auto-generated by `tools/build_wiki.py`. Do not edit by hand._",
        "",
        "## Overview",
        "",
        "- [overview](overview.md)",
        "- [log](log.md)",
        "",
    ]
    body_lines.extend(_section("Topics", "topics", TOPICS_DIR))
    body_lines.extend(_section("Concepts", "concepts", CONCEPTS_DIR))
    body_lines.extend(_section("Q&A", "qa", QA_DIR))

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text("\n".join(body_lines).rstrip() + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Log append
# ---------------------------------------------------------------------------

def append_log_line(line: str) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not LOG_PATH.exists():
        # Minimal bootstrap if someone deleted log.md.
        LOG_PATH.write_text(
            "---\nid: log\ntype: meta\ncfa_topic: \"\"\nstatus: draft\ntitle: Log\n---\n\n"
            "# Log\n\n_Auto-appended by tooling. New entries are added at the bottom._\n",
            encoding="utf-8",
        )
    with LOG_PATH.open("a", encoding="utf-8") as fh:
        fh.write(line.rstrip() + "\n")


# ---------------------------------------------------------------------------
# Frontmatter validation
# ---------------------------------------------------------------------------

def _iter_wiki_pages() -> Iterable[Path]:
    for path in WIKI_DIR.rglob("*.md"):
        if path.is_file():
            yield path


def _strip_type_prefix(identifier: str) -> str:
    for prefix in TYPE_PREFIXES:
        if identifier.startswith(prefix):
            return identifier[len(prefix):]
    return identifier


def validate_frontmatter() -> int:
    warnings = 0
    for path in _iter_wiki_pages():
        rel = path.relative_to(WIKI_DIR)
        try:
            post = read_markdown(path)
        except Exception as exc:  # noqa: BLE001
            print(f"[warn] {rel}: could not parse frontmatter: {exc}", file=sys.stderr)
            warnings += 1
            continue

        meta = post.metadata

        for field in REQUIRED_FIELDS:
            if field not in meta:
                print(f"[warn] {rel}: missing required frontmatter field '{field}'", file=sys.stderr)
                warnings += 1

        type_value = meta.get("type")
        if type_value is not None and type_value not in ALLOWED_TYPES:
            print(
                f"[warn] {rel}: invalid type '{type_value}' (allowed: {sorted(ALLOWED_TYPES)})",
                file=sys.stderr,
            )
            warnings += 1

        status_value = meta.get("status")
        if status_value is not None and status_value not in ALLOWED_STATUS:
            print(
                f"[warn] {rel}: invalid status '{status_value}' (allowed: {sorted(ALLOWED_STATUS)})",
                file=sys.stderr,
            )
            warnings += 1

        id_value = meta.get("id")
        if isinstance(id_value, str) and id_value:
            stem_expected = _strip_type_prefix(id_value)
            if stem_expected != path.stem:
                print(
                    f"[warn] {rel}: id '{id_value}' does not match filename stem '{path.stem}'",
                    file=sys.stderr,
                )
                warnings += 1

    return warnings


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    args = parse_args()

    if args.mode != "init":
        print(f"[err] unknown mode: {args.mode}", file=sys.stderr)
        return 2

    for directory in (TOPICS_DIR, CONCEPTS_DIR, QA_DIR):
        directory.mkdir(parents=True, exist_ok=True)

    topics_added = create_topics()
    concepts_added = create_concepts()
    print(f"[ok] topics created: {topics_added}")
    print(f"[ok] concepts created: {concepts_added}")

    regenerate_index()
    print(f"[ok] index refreshed: {INDEX_PATH.relative_to(WIKI_DIR.parent)}")

    warnings = validate_frontmatter()
    print(f"[ok] frontmatter validated: {warnings} warning(s)")

    log_line = (
        f"- `{now_iso()}` build init: "
        f"+{topics_added} topic(s), +{concepts_added} concept(s), "
        f"{warnings} warning(s)"
    )
    append_log_line(log_line)
    print(f"[ok] log appended")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
